<?php

return [
    ['name' => 'Afghanistan', 'alpha2' => 'AF', 'alpha3' => 'AFG', 'iso_num' => '4', 'prefix' => '93', 'region' => 'Asia'],
    ['name' => 'Åland Islands', 'alpha2' => 'AX', 'alpha3' => 'ALA', 'iso_num' => '248', 'prefix' => '358', 'region' => 'Europe'],
    ['name' => 'Albania', 'alpha2' => 'AL', 'alpha3' => 'ALB', 'iso_num' => '8', 'prefix' => '355', 'region' => 'Europe'],
    ['name' => 'Algeria', 'alpha2' => 'DZ', 'alpha3' => 'DZA', 'iso_num' => '12', 'prefix' => '213', 'region' => 'Africa'],
    ['name' => 'American Samoa', 'alpha2' => 'AS', 'alpha3' => 'ASM', 'iso_num' => '16', 'prefix' => '1-684', 'region' => 'Oceania'],
    ['name' => 'Andorra', 'alpha2' => 'AD', 'alpha3' => 'AND', 'iso_num' => '20', 'prefix' => '376', 'region' => 'Europe'],
    ['name' => 'Angola', 'alpha2' => 'AO', 'alpha3' => 'AGO', 'iso_num' => '24', 'prefix' => '244', 'region' => 'Africa'],
    ['name' => 'Anguilla', 'alpha2' => 'AI', 'alpha3' => 'AIA', 'iso_num' => '660', 'prefix' => '1-264', 'region' => 'Americas'],
    ['name' => 'Antarctica', 'alpha2' => 'AQ', 'alpha3' => 'ATA', 'iso_num' => '10', 'prefix' => '672', 'region' => ''],
    ['name' => 'Antigua and Barbuda', 'alpha2' => 'AG', 'alpha3' => 'ATG', 'iso_num' => '28', 'prefix' => '1-268', 'region' => 'Americas'],
    ['name' => 'Argentina', 'alpha2' => 'AR', 'alpha3' => 'ARG', 'iso_num' => '32', 'prefix' => '54', 'region' => 'Americas'],
    ['name' => 'Armenia', 'alpha2' => 'AM', 'alpha3' => 'ARM', 'iso_num' => '51', 'prefix' => '374', 'region' => 'Asia'],
    ['name' => 'Aruba', 'alpha2' => 'AW', 'alpha3' => 'ABW', 'iso_num' => '533', 'prefix' => '297', 'region' => 'Americas'],
    ['name' => 'Australia', 'alpha2' => 'AU', 'alpha3' => 'AUS', 'iso_num' => '36', 'prefix' => '61', 'region' => 'Oceania'],
    ['name' => 'Austria', 'alpha2' => 'AT', 'alpha3' => 'AUT', 'iso_num' => '40', 'prefix' => '43', 'region' => 'Europe'],
    ['name' => 'Azerbaijan', 'alpha2' => 'AZ', 'alpha3' => 'AZE', 'iso_num' => '31', 'prefix' => '994', 'region' => 'Asia'],
    ['name' => 'Bahamas', 'alpha2' => 'BS', 'alpha3' => 'BHS', 'iso_num' => '44', 'prefix' => '1-242', 'region' => 'Americas'],
    ['name' => 'Bahrain', 'alpha2' => 'BH', 'alpha3' => 'BHR', 'iso_num' => '48', 'prefix' => '973', 'region' => 'Asia'],
    ['name' => 'Bangladesh', 'alpha2' => 'BD', 'alpha3' => 'BGD', 'iso_num' => '50', 'prefix' => '880', 'region' => 'Asia'],
    ['name' => 'Barbados', 'alpha2' => 'BB', 'alpha3' => 'BRB', 'iso_num' => '52', 'prefix' => '1-246', 'region' => 'Americas'],
    ['name' => 'Belarus', 'alpha2' => 'BY', 'alpha3' => 'BLR', 'iso_num' => '112', 'prefix' => '375', 'region' => 'Europe'],
    ['name' => 'Belgium', 'alpha2' => 'BE', 'alpha3' => 'BEL', 'iso_num' => '56', 'prefix' => '32', 'region' => 'Europe'],
    ['name' => 'Belize', 'alpha2' => 'BZ', 'alpha3' => 'BLZ', 'iso_num' => '84', 'prefix' => '501', 'region' => 'Americas'],
    ['name' => 'Benin', 'alpha2' => 'BJ', 'alpha3' => 'BEN', 'iso_num' => '204', 'prefix' => '229', 'region' => 'Africa'],
    ['name' => 'Bermuda', 'alpha2' => 'BM', 'alpha3' => 'BMU', 'iso_num' => '60', 'prefix' => '1-441', 'region' => 'Americas'],
    ['name' => 'Bhutan', 'alpha2' => 'BT', 'alpha3' => 'BTN', 'iso_num' => '64', 'prefix' => '975', 'region' => 'Asia'],
    ['name' => 'Bolivia (Plurinational State of)', 'alpha2' => 'BO', 'alpha3' => 'BOL', 'iso_num' => '68', 'prefix' => '591', 'region' => 'Americas'],
    ['name' => 'Bonaire, Sint Eustatius and Saba', 'alpha2' => 'BQ', 'alpha3' => 'BES', 'iso_num' => '', 'prefix' => '', 'region' => 'Americas'],
    ['name' => 'Bosnia and Herzegovina', 'alpha2' => 'BA', 'alpha3' => 'BIH', 'iso_num' => '70', 'prefix' => '387', 'region' => 'Europe'],
    ['name' => 'Botswana', 'alpha2' => 'BW', 'alpha3' => 'BWA', 'iso_num' => '72', 'prefix' => '267', 'region' => 'Africa'],
    ['name' => 'Bouvet Island', 'alpha2' => 'BV', 'alpha3' => 'BVT', 'iso_num' => '78', 'prefix' => '47', 'region' => ''],
    ['name' => 'Brazil', 'alpha2' => 'BR', 'alpha3' => 'BRA', 'iso_num' => '76', 'prefix' => '55', 'region' => 'Americas'],
    ['name' => 'British Indian Ocean Territory', 'alpha2' => 'IO', 'alpha3' => 'IOT', 'iso_num' => '86', 'prefix' => '246', 'region' => ''],
    ['name' => 'Brunei Darussalam', 'alpha2' => 'BN', 'alpha3' => 'BRN', 'iso_num' => '96', 'prefix' => '673', 'region' => 'Asia'],
    ['name' => 'Bulgaria', 'alpha2' => 'BG', 'alpha3' => 'BGR', 'iso_num' => '100', 'prefix' => '359', 'region' => 'Europe'],
    ['name' => 'Burkina Faso', 'alpha2' => 'BF', 'alpha3' => 'BFA', 'iso_num' => '854', 'prefix' => '226', 'region' => 'Africa'],
    ['name' => 'Burundi', 'alpha2' => 'BI', 'alpha3' => 'BDI', 'iso_num' => '108', 'prefix' => '257', 'region' => 'Africa'],
    ['name' => 'Cambodia', 'alpha2' => 'KH', 'alpha3' => 'KHM', 'iso_num' => '116', 'prefix' => '855', 'region' => 'Asia'],
    ['name' => 'Cameroon', 'alpha2' => 'CM', 'alpha3' => 'CMR', 'iso_num' => '120', 'prefix' => '237', 'region' => 'Africa'],
    ['name' => 'Canada', 'alpha2' => 'CA', 'alpha3' => 'CAN', 'iso_num' => '124', 'prefix' => '1', 'region' => 'Americas'],
    ['name' => 'Cabo Verde', 'alpha2' => 'CV', 'alpha3' => 'CPV', 'iso_num' => '132', 'prefix' => '238', 'region' => 'Africa'],
    ['name' => 'Cayman Islands', 'alpha2' => 'KY', 'alpha3' => 'CYM', 'iso_num' => '136', 'prefix' => '1-345', 'region' => 'Americas'],
    ['name' => 'Central African Republic', 'alpha2' => 'CF', 'alpha3' => 'CAF', 'iso_num' => '140', 'prefix' => '236', 'region' => 'Africa'],
    ['name' => 'Chad', 'alpha2' => 'TD', 'alpha3' => 'TCD', 'iso_num' => '148', 'prefix' => '235', 'region' => 'Africa'],
    ['name' => 'Chile', 'alpha2' => 'CL', 'alpha3' => 'CHL', 'iso_num' => '152', 'prefix' => '56', 'region' => 'Americas'],
    ['name' => 'China', 'alpha2' => 'CN', 'alpha3' => 'CHN', 'iso_num' => '156', 'prefix' => '86', 'region' => 'Asia'],
    ['name' => 'Christmas Island', 'alpha2' => 'CX', 'alpha3' => 'CXR', 'iso_num' => '162', 'prefix' => '61', 'region' => ''],
    ['name' => 'Cocos (Keeling) Islands', 'alpha2' => 'CC', 'alpha3' => 'CCK', 'iso_num' => '166', 'prefix' => '61', 'region' => ''],
    ['name' => 'Colombia', 'alpha2' => 'CO', 'alpha3' => 'COL', 'iso_num' => '170', 'prefix' => '57', 'region' => 'Americas'],
    ['name' => 'Comoros', 'alpha2' => 'KM', 'alpha3' => 'COM', 'iso_num' => '174', 'prefix' => '269', 'region' => 'Africa'],
    ['name' => 'Congo', 'alpha2' => 'CG', 'alpha3' => 'COG', 'iso_num' => '178', 'prefix' => '242', 'region' => 'Africa'],
    ['name' => 'Congo (Democratic Republic of the)', 'alpha2' => 'CD', 'alpha3' => 'COD', 'iso_num' => '178', 'prefix' => '243', 'region' => 'Africa'],
    ['name' => 'Cook Islands', 'alpha2' => 'CK', 'alpha3' => 'COK', 'iso_num' => '184', 'prefix' => '682', 'region' => 'Oceania'],
    ['name' => 'Costa Rica', 'alpha2' => 'CR', 'alpha3' => 'CRI', 'iso_num' => '188', 'prefix' => '506', 'region' => 'Americas'],
    ['name' => 'Côte d\'Ivoire', 'alpha2' => 'CI', 'alpha3' => 'CIV', 'iso_num' => '384', 'prefix' => '225', 'region' => 'Africa'],
    ['name' => 'Croatia', 'alpha2' => 'HR', 'alpha3' => 'HRV', 'iso_num' => '191', 'prefix' => '385', 'region' => 'Europe'],
    ['name' => 'Cuba', 'alpha2' => 'CU', 'alpha3' => 'CUB', 'iso_num' => '192', 'prefix' => '53', 'region' => 'Americas'],
    ['name' => 'Curaçao', 'alpha2' => 'CW', 'alpha3' => 'CUW', 'iso_num' => '', 'prefix' => '', 'region' => 'Americas'],
    ['name' => 'Cyprus', 'alpha2' => 'CY', 'alpha3' => 'CYP', 'iso_num' => '196', 'prefix' => '357', 'region' => 'Asia'],
    ['name' => 'Czech Republic', 'alpha2' => 'CZ', 'alpha3' => 'CZE', 'iso_num' => '203', 'prefix' => '420', 'region' => 'Europe'],
    ['name' => 'Denmark', 'alpha2' => 'DK', 'alpha3' => 'DNK', 'iso_num' => '208', 'prefix' => '45', 'region' => 'Europe'],
    ['name' => 'Djibouti', 'alpha2' => 'DJ', 'alpha3' => 'DJI', 'iso_num' => '262', 'prefix' => '253', 'region' => 'Africa'],
    ['name' => 'Dominica', 'alpha2' => 'DM', 'alpha3' => 'DMA', 'iso_num' => '212', 'prefix' => '1-767', 'region' => 'Americas'],
    ['name' => 'Dominican Republic', 'alpha2' => 'DO', 'alpha3' => 'DOM', 'iso_num' => '214', 'prefix' => '1-809', 'region' => 'Americas'],
    ['name' => 'Ecuador', 'alpha2' => 'EC', 'alpha3' => 'ECU', 'iso_num' => '218', 'prefix' => '593', 'region' => 'Americas'],
    ['name' => 'Egypt', 'alpha2' => 'EG', 'alpha3' => 'EGY', 'iso_num' => '818', 'prefix' => '20', 'region' => 'Africa'],
    ['name' => 'El Salvador', 'alpha2' => 'SV', 'alpha3' => 'SLV', 'iso_num' => '222', 'prefix' => '503', 'region' => 'Americas'],
    ['name' => 'Equatorial Guinea', 'alpha2' => 'GQ', 'alpha3' => 'GNQ', 'iso_num' => '226', 'prefix' => '240', 'region' => 'Africa'],
    ['name' => 'Eritrea', 'alpha2' => 'ER', 'alpha3' => 'ERI', 'iso_num' => '232', 'prefix' => '291', 'region' => 'Africa'],
    ['name' => 'Estonia', 'alpha2' => 'EE', 'alpha3' => 'EST', 'iso_num' => '233', 'prefix' => '372', 'region' => 'Europe'],
    ['name' => 'Ethiopia', 'alpha2' => 'ET', 'alpha3' => 'ETH', 'iso_num' => '231', 'prefix' => '251', 'region' => 'Africa'],
    ['name' => 'Falkland Islands (Malvinas)', 'alpha2' => 'FK', 'alpha3' => 'FLK', 'iso_num' => '234', 'prefix' => '500', 'region' => 'Americas'],
    ['name' => 'Faroe Islands', 'alpha2' => 'FO', 'alpha3' => 'FRO', 'iso_num' => '238', 'prefix' => '298', 'region' => 'Europe'],
    ['name' => 'Fiji', 'alpha2' => 'FJ', 'alpha3' => 'FJI', 'iso_num' => '242', 'prefix' => '679', 'region' => 'Oceania'],
    ['name' => 'Finland', 'alpha2' => 'FI', 'alpha3' => 'FIN', 'iso_num' => '246', 'prefix' => '358', 'region' => 'Europe'],
    ['name' => 'France', 'alpha2' => 'FR', 'alpha3' => 'FRA', 'iso_num' => '250', 'prefix' => '33', 'region' => 'Europe'],
    ['name' => 'French Guiana', 'alpha2' => 'GF', 'alpha3' => 'GUF', 'iso_num' => '254', 'prefix' => '594', 'region' => 'Americas'],
    ['name' => 'French Polynesia', 'alpha2' => 'PF', 'alpha3' => 'PYF', 'iso_num' => '258', 'prefix' => '689', 'region' => 'Oceania'],
    ['name' => 'French Southern Territories', 'alpha2' => 'TF', 'alpha3' => 'ATF', 'iso_num' => '260', 'prefix' => '33', 'region' => ''],
    ['name' => 'Gabon', 'alpha2' => 'GA', 'alpha3' => 'GAB', 'iso_num' => '266', 'prefix' => '241', 'region' => 'Africa'],
    ['name' => 'Gambia', 'alpha2' => 'GM', 'alpha3' => 'GMB', 'iso_num' => '270', 'prefix' => '220', 'region' => 'Africa'],
    ['name' => 'Georgia', 'alpha2' => 'GE', 'alpha3' => 'GEO', 'iso_num' => '268', 'prefix' => '995', 'region' => 'Asia'],
    ['name' => 'Germany', 'alpha2' => 'DE', 'alpha3' => 'DEU', 'iso_num' => '276', 'prefix' => '49', 'region' => 'Europe'],
    ['name' => 'Ghana', 'alpha2' => 'GH', 'alpha3' => 'GHA', 'iso_num' => '288', 'prefix' => '233', 'region' => 'Africa'],
    ['name' => 'Gibraltar', 'alpha2' => 'GI', 'alpha3' => 'GIB', 'iso_num' => '292', 'prefix' => '350', 'region' => 'Europe'],
    ['name' => 'Greece', 'alpha2' => 'GR', 'alpha3' => 'GRC', 'iso_num' => '300', 'prefix' => '30', 'region' => 'Europe'],
    ['name' => 'Greenland', 'alpha2' => 'GL', 'alpha3' => 'GRL', 'iso_num' => '304', 'prefix' => '299', 'region' => 'Americas'],
    ['name' => 'Grenada', 'alpha2' => 'GD', 'alpha3' => 'GRD', 'iso_num' => '308', 'prefix' => '1-473', 'region' => 'Americas'],
    ['name' => 'Guadeloupe', 'alpha2' => 'GP', 'alpha3' => 'GLP', 'iso_num' => '312', 'prefix' => '590', 'region' => 'Americas'],
    ['name' => 'Guam', 'alpha2' => 'GU', 'alpha3' => 'GUM', 'iso_num' => '316', 'prefix' => '1-671', 'region' => 'Oceania'],
    ['name' => 'Guatemala', 'alpha2' => 'GT', 'alpha3' => 'GTM', 'iso_num' => '320', 'prefix' => '502', 'region' => 'Americas'],
    ['name' => 'Guernsey', 'alpha2' => 'GG', 'alpha3' => 'GGY', 'iso_num' => '1000', 'prefix' => '44', 'region' => 'Europe'],
    ['name' => 'Guinea', 'alpha2' => 'GN', 'alpha3' => 'GIN', 'iso_num' => '324', 'prefix' => '224', 'region' => 'Africa'],
    ['name' => 'Guinea-Bissau', 'alpha2' => 'GW', 'alpha3' => 'GNB', 'iso_num' => '624', 'prefix' => '245', 'region' => 'Africa'],
    ['name' => 'Guyana', 'alpha2' => 'GY', 'alpha3' => 'GUY', 'iso_num' => '328', 'prefix' => '592', 'region' => 'Americas'],
    ['name' => 'Haiti', 'alpha2' => 'HT', 'alpha3' => 'HTI', 'iso_num' => '332', 'prefix' => '509', 'region' => 'Americas'],
    ['name' => 'Heard Island and McDonald Islands', 'alpha2' => 'HM', 'alpha3' => 'HMD', 'iso_num' => '334', 'prefix' => '61', 'region' => ''],
    ['name' => 'Holy See', 'alpha2' => 'VA', 'alpha3' => 'VAT', 'iso_num' => '336', 'prefix' => '379', 'region' => 'Europe'],
    ['name' => 'Honduras', 'alpha2' => 'HN', 'alpha3' => 'HND', 'iso_num' => '340', 'prefix' => '504', 'region' => 'Americas'],
    ['name' => 'Hong Kong', 'alpha2' => 'HK', 'alpha3' => 'HKG', 'iso_num' => '344', 'prefix' => '852', 'region' => 'Asia'],
    ['name' => 'Hungary', 'alpha2' => 'HU', 'alpha3' => 'HUN', 'iso_num' => '348', 'prefix' => '36', 'region' => 'Europe'],
    ['name' => 'Iceland', 'alpha2' => 'IS', 'alpha3' => 'ISL', 'iso_num' => '352', 'prefix' => '354', 'region' => 'Europe'],
    ['name' => 'India', 'alpha2' => 'IN', 'alpha3' => 'IND', 'iso_num' => '356', 'prefix' => '91', 'region' => 'Asia'],
    ['name' => 'Indonesia', 'alpha2' => 'ID', 'alpha3' => 'IDN', 'iso_num' => '360', 'prefix' => '62', 'region' => 'Asia'],
    ['name' => 'Iran (Islamic Republic of)', 'alpha2' => 'IR', 'alpha3' => 'IRN', 'iso_num' => '364', 'prefix' => '98', 'region' => 'Asia'],
    ['name' => 'Iraq', 'alpha2' => 'IQ', 'alpha3' => 'IRQ', 'iso_num' => '368', 'prefix' => '964', 'region' => 'Asia'],
    ['name' => 'Ireland', 'alpha2' => 'IE', 'alpha3' => 'IRL', 'iso_num' => '372', 'prefix' => '353', 'region' => 'Europe'],
    ['name' => 'Isle of Man', 'alpha2' => 'IM', 'alpha3' => 'IMN', 'iso_num' => '833', 'prefix' => '44', 'region' => 'Europe'],
    ['name' => 'Israel', 'alpha2' => 'IL', 'alpha3' => 'ISR', 'iso_num' => '376', 'prefix' => '972', 'region' => 'Asia'],
    ['name' => 'Italy', 'alpha2' => 'IT', 'alpha3' => 'ITA', 'iso_num' => '380', 'prefix' => '39', 'region' => 'Europe'],
    ['name' => 'Jamaica', 'alpha2' => 'JM', 'alpha3' => 'JAM', 'iso_num' => '388', 'prefix' => '1-876', 'region' => 'Americas'],
    ['name' => 'Japan', 'alpha2' => 'JP', 'alpha3' => 'JPN', 'iso_num' => '392', 'prefix' => '81', 'region' => 'Asia'],
    ['name' => 'Jersey', 'alpha2' => 'JE', 'alpha3' => 'JEY', 'iso_num' => '1001', 'prefix' => '44', 'region' => 'Europe'],
    ['name' => 'Jordan', 'alpha2' => 'JO', 'alpha3' => 'JOR', 'iso_num' => '400', 'prefix' => '962', 'region' => 'Asia'],
    ['name' => 'Kazakhstan', 'alpha2' => 'KZ', 'alpha3' => 'KAZ', 'iso_num' => '398', 'prefix' => '7', 'region' => 'Asia'],
    ['name' => 'Kenya', 'alpha2' => 'KE', 'alpha3' => 'KEN', 'iso_num' => '404', 'prefix' => '254', 'region' => 'Africa'],
    ['name' => 'Kiribati', 'alpha2' => 'KI', 'alpha3' => 'KIR', 'iso_num' => '296', 'prefix' => '686', 'region' => 'Oceania'],
    ['name' => 'Korea (Democratic People\'s Republic of)', 'alpha2' => 'KP', 'alpha3' => 'PRK', 'iso_num' => '408', 'prefix' => '850', 'region' => 'Asia'],
    ['name' => 'Korea (Republic of)', 'alpha2' => 'KR', 'alpha3' => 'KOR', 'iso_num' => '410', 'prefix' => '82', 'region' => 'Asia'],
    ['name' => 'Kuwait', 'alpha2' => 'KW', 'alpha3' => 'KWT', 'iso_num' => '414', 'prefix' => '965', 'region' => 'Asia'],
    ['name' => 'Kyrgyzstan', 'alpha2' => 'KG', 'alpha3' => 'KGZ', 'iso_num' => '417', 'prefix' => '996', 'region' => 'Asia'],
    ['name' => 'Lao People\'s Democratic Republic', 'alpha2' => 'LA', 'alpha3' => 'LAO', 'iso_num' => '418', 'prefix' => '856', 'region' => 'Asia'],
    ['name' => 'Latvia', 'alpha2' => 'LV', 'alpha3' => 'LVA', 'iso_num' => '428', 'prefix' => '371', 'region' => 'Europe'],
    ['name' => 'Lebanon', 'alpha2' => 'LB', 'alpha3' => 'LBN', 'iso_num' => '422', 'prefix' => '961', 'region' => 'Asia'],
    ['name' => 'Lesotho', 'alpha2' => 'LS', 'alpha3' => 'LSO', 'iso_num' => '426', 'prefix' => '266', 'region' => 'Africa'],
    ['name' => 'Liberia', 'alpha2' => 'LR', 'alpha3' => 'LBR', 'iso_num' => '430', 'prefix' => '231', 'region' => 'Africa'],
    ['name' => 'Libya', 'alpha2' => 'LY', 'alpha3' => 'LBY', 'iso_num' => '434', 'prefix' => '218', 'region' => 'Africa'],
    ['name' => 'Liechtenstein', 'alpha2' => 'LI', 'alpha3' => 'LIE', 'iso_num' => '438', 'prefix' => '423', 'region' => 'Europe'],
    ['name' => 'Lithuania', 'alpha2' => 'LT', 'alpha3' => 'LTU', 'iso_num' => '440', 'prefix' => '370', 'region' => 'Europe'],
    ['name' => 'Luxembourg', 'alpha2' => 'LU', 'alpha3' => 'LUX', 'iso_num' => '442', 'prefix' => '352', 'region' => 'Europe'],
    ['name' => 'Macao', 'alpha2' => 'MO', 'alpha3' => 'MAC', 'iso_num' => '446', 'prefix' => '853', 'region' => 'Asia'],
    ['name' => 'Macedonia (the former Yugoslav Republic of)', 'alpha2' => 'MK', 'alpha3' => 'MKD', 'iso_num' => '807', 'prefix' => '389', 'region' => 'Europe'],
    ['name' => 'Madagascar', 'alpha2' => 'MG', 'alpha3' => 'MDG', 'iso_num' => '450', 'prefix' => '261', 'region' => 'Africa'],
    ['name' => 'Malawi', 'alpha2' => 'MW', 'alpha3' => 'MWI', 'iso_num' => '454', 'prefix' => '265', 'region' => 'Africa'],
    ['name' => 'Malaysia', 'alpha2' => 'MY', 'alpha3' => 'MYS', 'iso_num' => '458', 'prefix' => '60', 'region' => 'Asia'],
    ['name' => 'Maldives', 'alpha2' => 'MV', 'alpha3' => 'MDV', 'iso_num' => '462', 'prefix' => '960', 'region' => 'Asia'],
    ['name' => 'Mali', 'alpha2' => 'ML', 'alpha3' => 'MLI', 'iso_num' => '466', 'prefix' => '223', 'region' => 'Africa'],
    ['name' => 'Malta', 'alpha2' => 'MT', 'alpha3' => 'MLT', 'iso_num' => '470', 'prefix' => '356', 'region' => 'Europe'],
    ['name' => 'Marshall Islands', 'alpha2' => 'MH', 'alpha3' => 'MHL', 'iso_num' => '584', 'prefix' => '692', 'region' => 'Oceania'],
    ['name' => 'Martinique', 'alpha2' => 'MQ', 'alpha3' => 'MTQ', 'iso_num' => '474', 'prefix' => '596', 'region' => 'Americas'],
    ['name' => 'Mauritania', 'alpha2' => 'MR', 'alpha3' => 'MRT', 'iso_num' => '478', 'prefix' => '222', 'region' => 'Africa'],
    ['name' => 'Mauritius', 'alpha2' => 'MU', 'alpha3' => 'MUS', 'iso_num' => '480', 'prefix' => '230', 'region' => 'Africa'],
    ['name' => 'Mayotte', 'alpha2' => 'YT', 'alpha3' => 'MYT', 'iso_num' => '175', 'prefix' => '262', 'region' => 'Africa'],
    ['name' => 'Mexico', 'alpha2' => 'MX', 'alpha3' => 'MEX', 'iso_num' => '484', 'prefix' => '52', 'region' => 'Americas'],
    ['name' => 'Micronesia (Federated States of)', 'alpha2' => 'FM', 'alpha3' => 'FSM', 'iso_num' => '583', 'prefix' => '691', 'region' => 'Oceania'],
    ['name' => 'Moldova (Republic of)', 'alpha2' => 'MD', 'alpha3' => 'MDA', 'iso_num' => '498', 'prefix' => '373', 'region' => 'Europe'],
    ['name' => 'Monaco', 'alpha2' => 'MC', 'alpha3' => 'MCO', 'iso_num' => '482', 'prefix' => '377', 'region' => 'Europe'],
    ['name' => 'Mongolia', 'alpha2' => 'MN', 'alpha3' => 'MNG', 'iso_num' => '496', 'prefix' => '976', 'region' => 'Asia'],
    ['name' => 'Montenegro', 'alpha2' => 'ME', 'alpha3' => 'MNE', 'iso_num' => '499', 'prefix' => '382', 'region' => 'Europe'],
    ['name' => 'Montserrat', 'alpha2' => 'MS', 'alpha3' => 'MSR', 'iso_num' => '500', 'prefix' => '1-664', 'region' => 'Americas'],
    ['name' => 'Morocco', 'alpha2' => 'MA', 'alpha3' => 'MAR', 'iso_num' => '504', 'prefix' => '212', 'region' => 'Africa'],
    ['name' => 'Mozambique', 'alpha2' => 'MZ', 'alpha3' => 'MOZ', 'iso_num' => '508', 'prefix' => '258', 'region' => 'Africa'],
    ['name' => 'Myanmar', 'alpha2' => 'MM', 'alpha3' => 'MMR', 'iso_num' => '104', 'prefix' => '95', 'region' => 'Asia'],
    ['name' => 'Namibia', 'alpha2' => 'NA', 'alpha3' => 'NAM', 'iso_num' => '516', 'prefix' => '264', 'region' => 'Africa'],
    ['name' => 'Nauru', 'alpha2' => 'NR', 'alpha3' => 'NRU', 'iso_num' => '520', 'prefix' => '674', 'region' => 'Oceania'],
    ['name' => 'Nepal', 'alpha2' => 'NP', 'alpha3' => 'NPL', 'iso_num' => '524', 'prefix' => '977', 'region' => 'Asia'],
    ['name' => 'Netherlands', 'alpha2' => 'NL', 'alpha3' => 'NLD', 'iso_num' => '528', 'prefix' => '31', 'region' => 'Europe'],
    ['name' => 'New Caledonia', 'alpha2' => 'NC', 'alpha3' => 'NCL', 'iso_num' => '540', 'prefix' => '687', 'region' => 'Oceania'],
    ['name' => 'New Zealand', 'alpha2' => 'NZ', 'alpha3' => 'NZL', 'iso_num' => '554', 'prefix' => '64', 'region' => 'Oceania'],
    ['name' => 'Nicaragua', 'alpha2' => 'NI', 'alpha3' => 'NIC', 'iso_num' => '558', 'prefix' => '505', 'region' => 'Americas'],
    ['name' => 'Niger', 'alpha2' => 'NE', 'alpha3' => 'NER', 'iso_num' => '562', 'prefix' => '227', 'region' => 'Africa'],
    ['name' => 'Nigeria', 'alpha2' => 'NG', 'alpha3' => 'NGA', 'iso_num' => '566', 'prefix' => '234', 'region' => 'Africa'],
    ['name' => 'Niue', 'alpha2' => 'NU', 'alpha3' => 'NIU', 'iso_num' => '570', 'prefix' => '683', 'region' => 'Oceania'],
    ['name' => 'Norfolk Island', 'alpha2' => 'NF', 'alpha3' => 'NFK', 'iso_num' => '574', 'prefix' => '672', 'region' => 'Oceania'],
    ['name' => 'Northern Mariana Islands', 'alpha2' => 'MP', 'alpha3' => 'MNP', 'iso_num' => '580', 'prefix' => '1-670', 'region' => 'Oceania'],
    ['name' => 'Norway', 'alpha2' => 'NO', 'alpha3' => 'NOR', 'iso_num' => '578', 'prefix' => '47', 'region' => 'Europe'],
    ['name' => 'Oman', 'alpha2' => 'OM', 'alpha3' => 'OMN', 'iso_num' => '512', 'prefix' => '968', 'region' => 'Asia'],
    ['name' => 'Pakistan', 'alpha2' => 'PK', 'alpha3' => 'PAK', 'iso_num' => '586', 'prefix' => '92', 'region' => 'Asia'],
    ['name' => 'Palau', 'alpha2' => 'PW', 'alpha3' => 'PLW', 'iso_num' => '585', 'prefix' => '680', 'region' => 'Oceania'],
    ['name' => 'Palestine, State of', 'alpha2' => 'PS', 'alpha3' => 'PSE', 'iso_num' => '275', 'prefix' => '970', 'region' => 'Asia'],
    ['name' => 'Panama', 'alpha2' => 'PA', 'alpha3' => 'PAN', 'iso_num' => '591', 'prefix' => '507', 'region' => 'Americas'],
    ['name' => 'Papua New Guinea', 'alpha2' => 'PG', 'alpha3' => 'PNG', 'iso_num' => '598', 'prefix' => '675', 'region' => 'Oceania'],
    ['name' => 'Paraguay', 'alpha2' => 'PY', 'alpha3' => 'PRY', 'iso_num' => '600', 'prefix' => '595', 'region' => 'Americas'],
    ['name' => 'Peru', 'alpha2' => 'PE', 'alpha3' => 'PER', 'iso_num' => '604', 'prefix' => '51', 'region' => 'Americas'],
    ['name' => 'Philippines', 'alpha2' => 'PH', 'alpha3' => 'PHL', 'iso_num' => '608', 'prefix' => '63', 'region' => 'Asia'],
    ['name' => 'Pitcairn', 'alpha2' => 'PN', 'alpha3' => 'PCN', 'iso_num' => '612', 'prefix' => '64', 'region' => 'Oceania'],
    ['name' => 'Poland', 'alpha2' => 'PL', 'alpha3' => 'POL', 'iso_num' => '616', 'prefix' => '48', 'region' => 'Europe'],
    ['name' => 'Portugal', 'alpha2' => 'PT', 'alpha3' => 'PRT', 'iso_num' => '620', 'prefix' => '351', 'region' => 'Europe'],
    ['name' => 'Puerto Rico', 'alpha2' => 'PR', 'alpha3' => 'PRI', 'iso_num' => '630', 'prefix' => '1', 'region' => 'Americas'],
    ['name' => 'Qatar', 'alpha2' => 'QA', 'alpha3' => 'QAT', 'iso_num' => '634', 'prefix' => '974', 'region' => 'Asia'],
    ['name' => 'Réunion', 'alpha2' => 'RE', 'alpha3' => 'REU', 'iso_num' => '638', 'prefix' => '262', 'region' => 'Africa'],
    ['name' => 'Romania', 'alpha2' => 'RO', 'alpha3' => 'ROU', 'iso_num' => '642', 'prefix' => '40', 'region' => 'Europe'],
    ['name' => 'Russian Federation', 'alpha2' => 'RU', 'alpha3' => 'RUS', 'iso_num' => '643', 'prefix' => '7', 'region' => 'Europe'],
    ['name' => 'Rwanda', 'alpha2' => 'RW', 'alpha3' => 'RWA', 'iso_num' => '646', 'prefix' => '250', 'region' => 'Africa'],
    ['name' => 'Saint Barthélemy', 'alpha2' => 'BL', 'alpha3' => 'BLM', 'iso_num' => '652', 'prefix' => '590', 'region' => 'Americas'],
    ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'alpha2' => 'SH', 'alpha3' => 'SHN', 'iso_num' => '654', 'prefix' => '290', 'region' => 'Africa'],
    ['name' => 'Saint Kitts and Nevis', 'alpha2' => 'KN', 'alpha3' => 'KNA', 'iso_num' => '659', 'prefix' => '1-869', 'region' => 'Americas'],
    ['name' => 'Saint Lucia', 'alpha2' => 'LC', 'alpha3' => 'LCA', 'iso_num' => '662', 'prefix' => '1-758', 'region' => 'Americas'],
    ['name' => 'Saint Martin (French part)', 'alpha2' => 'MF', 'alpha3' => 'MAF', 'iso_num' => '663', 'prefix' => '590', 'region' => 'Americas'],
    ['name' => 'Saint Pierre and Miquelon', 'alpha2' => 'PM', 'alpha3' => 'SPM', 'iso_num' => '666', 'prefix' => '508', 'region' => 'Americas'],
    ['name' => 'Saint Vincent and the Grenadines', 'alpha2' => 'VC', 'alpha3' => 'VCT', 'iso_num' => '670', 'prefix' => '1-784', 'region' => 'Americas'],
    ['name' => 'Samoa', 'alpha2' => 'WS', 'alpha3' => 'WSM', 'iso_num' => '882', 'prefix' => '685', 'region' => 'Oceania'],
    ['name' => 'San Marino', 'alpha2' => 'SM', 'alpha3' => 'SMR', 'iso_num' => '674', 'prefix' => '378', 'region' => 'Europe'],
    ['name' => 'Sao Tome and Principe', 'alpha2' => 'ST', 'alpha3' => 'STP', 'iso_num' => '678', 'prefix' => '239', 'region' => 'Africa'],
    ['name' => 'Saudi Arabia', 'alpha2' => 'SA', 'alpha3' => 'SAU', 'iso_num' => '682', 'prefix' => '966', 'region' => 'Asia'],
    ['name' => 'Senegal', 'alpha2' => 'SN', 'alpha3' => 'SEN', 'iso_num' => '686', 'prefix' => '221', 'region' => 'Africa'],
    ['name' => 'Serbia', 'alpha2' => 'RS', 'alpha3' => 'SRB', 'iso_num' => '688', 'prefix' => '381', 'region' => 'Europe'],
    ['name' => 'Seychelles', 'alpha2' => 'SC', 'alpha3' => 'SYC', 'iso_num' => '690', 'prefix' => '248', 'region' => 'Africa'],
    ['name' => 'Sierra Leone', 'alpha2' => 'SL', 'alpha3' => 'SLE', 'iso_num' => '694', 'prefix' => '232', 'region' => 'Africa'],
    ['name' => 'Singapore', 'alpha2' => 'SG', 'alpha3' => 'SGP', 'iso_num' => '702', 'prefix' => '65', 'region' => 'Asia'],
    ['name' => 'Sint Maarten (Dutch part)', 'alpha2' => 'SX', 'alpha3' => 'SXM', 'iso_num' => '', 'prefix' => '', 'region' => 'Americas'],
    ['name' => 'Slovakia', 'alpha2' => 'SK', 'alpha3' => 'SVK', 'iso_num' => '703', 'prefix' => '421', 'region' => 'Europe'],
    ['name' => 'Slovenia', 'alpha2' => 'SI', 'alpha3' => 'SVN', 'iso_num' => '705', 'prefix' => '386', 'region' => 'Europe'],
    ['name' => 'Solomon Islands', 'alpha2' => 'SB', 'alpha3' => 'SLB', 'iso_num' => '90', 'prefix' => '677', 'region' => 'Oceania'],
    ['name' => 'Somalia', 'alpha2' => 'SO', 'alpha3' => 'SOM', 'iso_num' => '706', 'prefix' => '252', 'region' => 'Africa'],
    ['name' => 'South Africa', 'alpha2' => 'ZA', 'alpha3' => 'ZAF', 'iso_num' => '710', 'prefix' => '27', 'region' => 'Africa'],
    ['name' => 'South Georgia and the South Sandwich Islands', 'alpha2' => 'GS', 'alpha3' => 'SGS', 'iso_num' => '239', 'prefix' => '66', 'region' => ''],
    ['name' => 'South Sudan', 'alpha2' => 'SS', 'alpha3' => 'SSD', 'iso_num' => '728', 'prefix' => '211', 'region' => 'Africa'],
    ['name' => 'Spain', 'alpha2' => 'ES', 'alpha3' => 'ESP', 'iso_num' => '724', 'prefix' => '34', 'region' => 'Europe'],
    ['name' => 'Sri Lanka', 'alpha2' => 'LK', 'alpha3' => 'LKA', 'iso_num' => '144', 'prefix' => '94', 'region' => 'Asia'],
    ['name' => 'Sudan', 'alpha2' => 'SD', 'alpha3' => 'SDN', 'iso_num' => '729', 'prefix' => '249', 'region' => 'Africa'],
    ['name' => 'Suriname', 'alpha2' => 'SR', 'alpha3' => 'SUR', 'iso_num' => '740', 'prefix' => '597', 'region' => 'Americas'],
    ['name' => 'Svalbard and Jan Mayen', 'alpha2' => 'SJ', 'alpha3' => 'SJM', 'iso_num' => '744', 'prefix' => '47', 'region' => 'Europe'],
    ['name' => 'Swaziland', 'alpha2' => 'SZ', 'alpha3' => 'SWZ', 'iso_num' => '748', 'prefix' => '268', 'region' => 'Africa'],
    ['name' => 'Sweden', 'alpha2' => 'SE', 'alpha3' => 'SWE', 'iso_num' => '752', 'prefix' => '46', 'region' => 'Europe'],
    ['name' => 'Switzerland', 'alpha2' => 'CH', 'alpha3' => 'CHE', 'iso_num' => '756', 'prefix' => '41', 'region' => 'Europe'],
    ['name' => 'Syrian Arab Republic', 'alpha2' => 'SY', 'alpha3' => 'SYR', 'iso_num' => '760', 'prefix' => '963', 'region' => 'Asia'],
    ['name' => 'Taiwan, Province of China', 'alpha2' => 'TW', 'alpha3' => 'TWN', 'iso_num' => '18', 'prefix' => '886', 'region' => 'Asia'],
    ['name' => 'Tajikistan', 'alpha2' => 'TJ', 'alpha3' => 'TJK', 'iso_num' => '762', 'prefix' => '992', 'region' => 'Asia'],
    ['name' => 'Tanzania, United Republic of', 'alpha2' => 'TZ', 'alpha3' => 'TZA', 'iso_num' => '834', 'prefix' => '255', 'region' => 'Africa'],
    ['name' => 'Thailand', 'alpha2' => 'TH', 'alpha3' => 'THA', 'iso_num' => '764', 'prefix' => '66', 'region' => 'Asia'],
    ['name' => 'Timor-Leste', 'alpha2' => 'TL', 'alpha3' => 'TLS', 'iso_num' => '626', 'prefix' => '670', 'region' => 'Asia'],
    ['name' => 'Togo', 'alpha2' => 'TG', 'alpha3' => 'TGO', 'iso_num' => '768', 'prefix' => '676', 'region' => 'Africa'],
    ['name' => 'Tokelau', 'alpha2' => 'TK', 'alpha3' => 'TKL', 'iso_num' => '772', 'prefix' => '690', 'region' => 'Oceania'],
    ['name' => 'Tonga', 'alpha2' => 'TO', 'alpha3' => 'TON', 'iso_num' => '776', 'prefix' => '676', 'region' => 'Oceania'],
    ['name' => 'Trinidad and Tobago', 'alpha2' => 'TT', 'alpha3' => 'TTO', 'iso_num' => '780', 'prefix' => '1-868', 'region' => 'Americas'],
    ['name' => 'Tunisia', 'alpha2' => 'TN', 'alpha3' => 'TUN', 'iso_num' => '788', 'prefix' => '216', 'region' => 'Africa'],
    ['name' => 'Turkey', 'alpha2' => 'TR', 'alpha3' => 'TUR', 'iso_num' => '792', 'prefix' => '90', 'region' => 'Asia'],
    ['name' => 'Turkmenistan', 'alpha2' => 'TM', 'alpha3' => 'TKM', 'iso_num' => '795', 'prefix' => '993', 'region' => 'Asia'],
    ['name' => 'Turks and Caicos Islands', 'alpha2' => 'TC', 'alpha3' => 'TCA', 'iso_num' => '796', 'prefix' => '1-649', 'region' => 'Americas'],
    ['name' => 'Tuvalu', 'alpha2' => 'TV', 'alpha3' => 'TUV', 'iso_num' => '798', 'prefix' => '688', 'region' => 'Oceania'],
    ['name' => 'Uganda', 'alpha2' => 'UG', 'alpha3' => 'UGA', 'iso_num' => '800', 'prefix' => '256', 'region' => 'Africa'],
    ['name' => 'Ukraine', 'alpha2' => 'UA', 'alpha3' => 'UKR', 'iso_num' => '804', 'prefix' => '380', 'region' => 'Europe'],
    ['name' => 'United Arab Emirates', 'alpha2' => 'AE', 'alpha3' => 'ARE', 'iso_num' => '784', 'prefix' => '971', 'region' => 'Asia'],
    ['name' => 'United Kingdom of Great Britain and Northern Ireland', 'alpha2' => 'GB', 'alpha3' => 'GBR', 'iso_num' => '826', 'prefix' => '44', 'region' => 'Europe'],
    ['name' => 'United States of America', 'alpha2' => 'US', 'alpha3' => 'USA', 'iso_num' => '840', 'prefix' => '1', 'region' => 'Americas'],
    ['name' => 'United States Minor Outlying Islands', 'alpha2' => 'UM', 'alpha3' => 'UMI', 'iso_num' => '581', 'prefix' => '699', 'region' => ''],
    ['name' => 'Uruguay', 'alpha2' => 'UY', 'alpha3' => 'URY', 'iso_num' => '858', 'prefix' => '598', 'region' => 'Americas'],
    ['name' => 'Uzbekistan', 'alpha2' => 'UZ', 'alpha3' => 'UZB', 'iso_num' => '860', 'prefix' => '998', 'region' => 'Asia'],
    ['name' => 'Vanuatu', 'alpha2' => 'VU', 'alpha3' => 'VUT', 'iso_num' => '548', 'prefix' => '678', 'region' => 'Oceania'],
    ['name' => 'Venezuela (Bolivarian Republic of)', 'alpha2' => 'VE', 'alpha3' => 'VEN', 'iso_num' => '862', 'prefix' => '58', 'region' => 'Americas'],
    ['name' => 'Viet Nam', 'alpha2' => 'VN', 'alpha3' => 'VNM', 'iso_num' => '704', 'prefix' => '84', 'region' => 'Asia'],
    ['name' => 'Virgin Islands (British)', 'alpha2' => 'VG', 'alpha3' => 'VGB', 'iso_num' => '850', 'prefix' => '1-284', 'region' => 'Americas'],
    ['name' => 'Virgin Islands (U.S.)', 'alpha2' => 'VI', 'alpha3' => 'VIR', 'iso_num' => '850', 'prefix' => '1-340', 'region' => 'Americas'],
    ['name' => 'Wallis and Futuna', 'alpha2' => 'WF', 'alpha3' => 'WLF', 'iso_num' => '876', 'prefix' => '681', 'region' => 'Oceania'],
    ['name' => 'Western Sahara', 'alpha2' => 'EH', 'alpha3' => 'ESH', 'iso_num' => '762', 'prefix' => '212', 'region' => 'Africa'],
    ['name' => 'Yemen', 'alpha2' => 'YE', 'alpha3' => 'YEM', 'iso_num' => '887', 'prefix' => '967', 'region' => 'Asia'],
    ['name' => 'Zambia', 'alpha2' => 'ZM', 'alpha3' => 'ZMB', 'iso_num' => '894', 'prefix' => '260', 'region' => 'Africa'],
    ['name' => 'Zimbabwe', 'alpha2' => 'ZW', 'alpha3' => 'ZWE', 'iso_num' => '716', 'prefix' => '263', 'region' => 'Africa'],
];
